set(FLASHINFER_GEN_HEAD_DIMS 64 128 256 512)
set(FLASHINFER_GEN_KV_LAYOUTS 0 1)
set(FLASHINFER_GEN_POS_ENCODING_MODES 0 )
set(FLASHINFER_GEN_USE_FP16_QK_REDUCTIONS "false")
set(FLASHINFER_GEN_MASK_MODES 0 1 2)
set(FLASHINFER_ENABLE_F16 ON)
set(FLASHINFER_ENABLE_BF16 OFF)
set(FLASHINFER_ENABLE_FP8_E4M3 OFF)
set(FLASHINFER_ENABLE_FP8_E5M2 OFF)
set(FLASHINFER_GEN_HEAD_DIMS_SM_90 64,64 128,128 256,256 512,512)

set(FLASHINFER_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps/flashinfer)

file(MAKE_DIRECTORY ${FLASHINFER_ROOT_DIR}/src/generated)

set(AOT_GENERATE_COMMAND
    ${Python3_EXECUTABLE} -m aot_build_utils.generate --path
    ${FLASHINFER_ROOT_DIR}/src/generated --head_dims ${FLASHINFER_GEN_HEAD_DIMS}
    --pos_encoding_modes ${FLASHINFER_GEN_POS_ENCODING_MODES} --use_fp16_qk_reductions
    ${FLASHINFER_GEN_USE_FP16_QK_REDUCTIONS} --mask_modes ${FLASHINFER_GEN_MASK_MODES} --enable_f16
    ${FLASHINFER_ENABLE_F16} --enable_bf16 ${FLASHINFER_ENABLE_BF16}
    --enable_fp8_e4m3 ${FLASHINFER_ENABLE_FP8_E4M3} --enable_fp8_e5m2
    ${FLASHINFER_ENABLE_FP8_E5M2})

execute_process(COMMAND ${AOT_GENERATE_COMMAND} WORKING_DIRECTORY ${FLASHINFER_ROOT_DIR})

set(AOT_GENERATE_DISPATCH_COMMAND
    ${Python3_EXECUTABLE} -m aot_build_utils.generate_dispatch_inc --path
    ${FLASHINFER_ROOT_DIR}/src/generated/dispatch.inc --head_dims ${FLASHINFER_GEN_HEAD_DIMS}
    --pos_encoding_modes ${FLASHINFER_GEN_POS_ENCODING_MODES} --use_fp16_qk_reductions
    ${FLASHINFER_GEN_USE_FP16_QK_REDUCTIONS} --mask_modes ${FLASHINFER_GEN_MASK_MODES} 
    --head_dims_sm90 ${FLASHINFER_GEN_HEAD_DIMS_SM_90})

execute_process(COMMAND ${AOT_GENERATE_DISPATCH_COMMAND} WORKING_DIRECTORY ${FLASHINFER_ROOT_DIR})


list(APPEND FLEXFLOW_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/deps/flashinfer/include)
list(APPEND FLEXFLOW_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/deps/flashinfer/src)

